### ISSUE TITLE
PanResponde weird behavior if view is zoomed

### ISSUE THREAD

**Issue by martinschurmann** [DuDigital/react-native-zoomable-view#15]
Hey! So i have an ReactNativeZoomableView, and as a child a draggable component. (I can drag it with a PanResponder). If the image has no zoom it can move without any issues, but if I move it around while the image is zoomed theres a weird behavior, the component moves a lot more, for example. there is a 1.8 zoom, the draggable component is at the top of the screen, but if I move my finger to the middle, the component moves to the bottom of the screen. Is there any way to fix this?

**Comment by jayan2019** [comment]
Have you resolved this issue? How if yes?
