### ISSUE TITLE
ComponentWillMount deprecated

### ISSUE THREAD

**Issue by hlotvonen** [DuDigital/react-native-zoomable-view#17]
Hi!
Thanks for this nice package, it suits my needs perfectly :-)
Recently I've been getting a warning message on my app though:

> Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.
> 
> Please update the following components: ReactNativeZoomableView
> 
> Learn more about this warning here:
> https://fb.me/react-async-component-lifecycle-hooks

**Comment by skantus** [comment]
@hlotvonen could you suggest a PR for this?

**Comment by SimonErich** [comment]
Fixed in v1.0.14.
Thanks @jhainaua for the pull request. :)
