### ISSUE TITLE
when top to pull conmopenet is moving down

### ISSUE THREAD

**Issue by naseemakhtar994** [DuDigital/react-native-zoomable-view#20]

**Comment by SNWStaff** [comment]
Did you find a solution  ?

**Comment by SimonErich** [comment]
@SNWStaff @naseemakhtar994 can you provide an example repo showcasing the problem, then I will have a look at it.

**Comment by SimonErich** [comment]
Please elaborate more what you mean or what the problem is. I will close this for now. Feel free to open it again with a working example, that I can look at.
