### ISSUE TITLE
deeper zoom scroll out or skip out

### ISSUE THREAD

**Issue by grappesm** [DuDigital/react-native-zoomable-view#24]
I am displaying some large image inside. I set max Zoom to 5 (or higher). The first zoom with 2 fingers usually is OK. If I zoom more, the center point of zoom is moving out, or is zoom (with 2 fingers) again it is not easy zoom to point I want to. The point is moving away during zooming. Sometimes if I start second zoom (put 1st finger and after 1 second I puth the 2nd finger), the image skips.

**Comment by SimonErich** [comment]
Could you please provide an example on expo or in a seperate repo, so I can see what the problem is?

**Comment by sugarman9907** [comment]
I have same issue.

**Comment by dudyn5ky1** [comment]
Any solution for this?

**Comment by SimonErich** [comment]
Can you guys please provide a working for this.
You can use https://github.com/DuDigital/react-native-zoomable-view-example as a basis.
I am closing this for now. If you have the example, please open it again.
