### ISSUE TITLE
Scroll disable request

### ISSUE THREAD

**Issue by destwofe** [DuDigital/react-native-zoomable-view#25]
Thank it good lib,
may is ask more feature
scroll disable,
currently i have a problem when i use zoomable view with scroll view
```
<ScrollView>
<ZoomableView>
...
</ZoomableView>
</ScrollView>
```

**Comment by SimonErich** [comment]
Please elaborate a little more what the problem is and provide a working example on a repo or expo, so I can see what the problem is!

**Comment by loikfb** [comment]
@destwofe You can simply toggle scrollEnabled prop of your scroll view in onZoomBefore and onZoomAfter callbacks of ZoomableView.

**Comment by destwofe** [comment]
https://github.com/DuDigital/react-native-zoomable-view/issues/25#issuecomment-565801110

**Comment by destwofe** [comment]
https://github.com/DuDigital/react-native-zoomable-view/issues/25#issuecomment-565801110
Thank, i use onZoomAfter to get lastest zoomlevel and disable zoomable when zoomable != 1

**Comment by aravi365** [comment]
> [#25 (comment)](https://github.com/DuDigital/react-native-zoomable-view/issues/25#issuecomment-565801110)
> Thank, i use onZoomAfter to get lastest zoomlevel and disable zoomable when zoomable != 1

do you have some code to share?
