### ISSUE TITLE
Missing Type definition in npm package

### ISSUE THREAD

**Issue by SaeedZhiany** [DuDigital/react-native-zoomable-view#26]
Type definition file does not exist in npm package that installed in a RN project. so importing in typescript projects causes error;

```
import ReactNativeZoomableView from '@dudigital/react-native-zoomable-view/src/ReactNativeZoomableView';
```

![image](https://user-images.githubusercontent.com/13766432/69916476-a24bf100-1470-11ea-9c3c-d74757c8989d.png)

![image](https://user-images.githubusercontent.com/13766432/69916502-f3f47b80-1470-11ea-9765-1c1b322cfee7.png)

**Comment by SimonErich** [comment]
Thanks to @adamaveray v1.0.15 was just released with types
