### ISSUE TITLE
bindToBorders not working

### ISSUE THREAD

**Issue by SerdarMustafa1** [DuDigital/react-native-zoomable-view#27]
When I zoom, the image just enlarges and covers the entire screen. Whether I use bindToBorders or try other workarounds like wrapping in different size views, I still get the same effect. 

```/* eslint-disable react/jsx-boolean-value */
import React from "react";
import {
  Container,
  Text,
  Button,
  View,
  Icon,
  StyleProvider,
} from "native-base";
import {
  ImageBackground,
  Image,
  TouchableOpacity,
  TextInput,
  Modal,
  Dimensions,
} from "react-native";

import ImageZoom from "react-native-image-pan-zoom";

import ReactNativeZoomableView from "@dudigital/react-native-zoomable-view/src/ReactNativeZoomableView";

import styles from "./ShotLoggerStyles";
import texts from "../../Style/texts";

import getTheme from "../../native-base-theme/components";
import marksmenOne from "../../native-base-theme/variables/marksmenOne";

import HeaderComponent from "../../Components/Header/Header";
import FooterComponent from "../../Components/Footer/FooterComponent";
import ChangeWeapon from "../../Components/ChangeWeapon";
import WeaponsModal from "../../Components/Modal/WeaponsModal";
import Loader from "../../Components/Loader/Loader";

const mainBG = require("../../assets/Backgrounds/metal.jpg");
const contentBG = require("../../assets/Backgrounds/training.jpg");

const ShotLoggerView = props => {
  const {
    leftPress,
    log,
    addShot,
    removeShot,
    updateShots,
    updateScore,
    changeWeaponHandler,
    _takeImageHandler,
    saveLog,
    weaponModalVisible,
    toggleWeaponModal,
    loading,
    displayHeight,
    logOutZoomState,
  } = props;

  return (
    <Container>
      <StyleProvider style={getTheme(marksmenOne)}>
        <ImageBackground source={mainBG} style={styles.mainBG}>
          <Loader visible={loading} />
          <HeaderComponent
            headerTitle="Logging Shots"
            leftPress={leftPress}
            leftAction="close"
          />
          <View style={styles.content}>
            {!log.image ? (
              <>
                <ChangeWeapon
                  weaponModalVisible={weaponModalVisible}
                  onChangeWeapon={changeWeaponHandler}
                  toggleWeaponModal={toggleWeaponModal}
                />
                <ImageBackground style={styles.noImage} source={contentBG}>
                  <Text style={texts.headerTitle}>
                    Take a picture of your target
                  </Text>

                  <Button
                    icon
                    style={styles.buttonPrimary}
                    onPress={() => _takeImageHandler()}
                  >
                    <Icon style={styles.buttonIcon} name="camera" />
                  </Button>
                </ImageBackground>
              </>
            ) : (
              <>
                <View style={styles.details}>
                  <View style={styles.detailsItem}>
                    <Text style={texts.bodyWhite}>Shots</Text>
                    <TextInput
                      style={styles.input}
                      defaultValue={log.shots.toString()}
                      editable={false}
                    />
                  </View>
                  <View style={styles.detailsItem}>
                    <Text style={texts.bodyWhite}>Score</Text>
                    <TextInput
                      style={styles.input}
                      onChangeText={value => updateScore(value)}
                      clearTextOnFocus
                      keyboardType="number-pad"
                      returnKeyType="done"
                    />
                  </View>
                </View>


                <View style={{ width: 300 }}>
                  <ReactNativeZoomableView
                    maxZoom={2.5}
                    minZoom={1}
                    zoomStep={0.5}
                    initialZoom={1}
                    bindToBorders={true}
                    // onZoomAfter={logOutZoomState}
                  >
                    <TouchableOpacity
                      activeOpacity={1}
                      style={styles.pointer}
                      onPress={evt => addShot(evt.nativeEvent)}
                    >
                      <View
                        style={[
                          styles.instructions,
                          log.heatmap.length > 0
                            ? { zIndex: -5 }
                            : { zIndex: 20 },
                        ]}
                      >
                        <Text style={texts.headerBody}>
                          Tap the picture to add &amp; remove shots.
                        </Text>
                      </View>

                      <Image
                        style={{ width: 300, height: 300 }}
                        source={{ uri: `data:image/jpg;base64,${log.image}` }}
                      />

                      {log.heatmap.length > 0 &&
                        log.heatmap.map((shot, index) => {
                          return (
                            <TouchableOpacity
                              key={index}
                              onPress={() => removeShot(index)}
                              style={[
                                styles.shot,
                                { left: shot.x - 10, top: shot.y - 10 },
                              ]}
                            />
                          );
                        })}
                    </TouchableOpacity>
                  </ReactNativeZoomableView>
                </View>
              </>
            )}
          </View>
          <FooterComponent
            rightAction={saveLog}
            rightActionText="Save shots"
            rightActionDisable={!log.image}
          />
        </ImageBackground>
      </StyleProvider>
    </Container>
  );
};

export default ShotLoggerView;
```

**Comment by SimonErich** [comment]
I don't understand exactly what you mean. Please provide a full example on Expo, so I can see what the problem is.
The example you provided, is not very helpful, because all the styles are missing and I cannot guess what's behind this!
Please provide a full  example

**Comment by tamirla** [comment]
@SimonErich I'm experiencing a similar behaviour, this is my code:


    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <View
        style={{
          width: 200,
          height: 200,
        }}>
        <ReactNativeZoomableView
          bindToBorders={true}
          style={{
            width: 200,
            height: 200,
          }}>
          <Image uri={path} />
        </ReactNativeZoomableView>
      </View>
    </View>


see attached video that demonstrate the behaviour. I expected the rectangle of the image to remain in same position & size in the screen and not to increase in size will increasing the image, unless I didn't understand the purpose of bindToBorders
![Screen-Recording-2020-01-29-at-11 11 11](https://user-images.githubusercontent.com/10025214/73343402-41327500-4289-11ea-987d-49ed90459004.gif)

**Comment by chandniKkpl** [comment]
I am using it but my image width is cutting both sides around 10%. 
Here is my code:

 <View style={{ flex: 1 }}>

                        <ReactNativeZoomableView
                            maxZoom={1.5}
                            minZoom={0.5}
                            zoomStep={0.5}
                            initialZoom={1}
                            bindToBorders={false}
                            onZoomAfter={this.logOutZoomState}
                            style={{
                                padding: 10,
                                backgroundColor: 'white',
                            }}
                        >
                            <Image source={this.state.imgUrlForZooming} style={{ flex: 1, width: null, height:'100%' }} />
                        </ReactNativeZoomableView>

                    </View>

Please let me know.
Thanks

**Comment by SimonErich** [comment]
> @SimonErich I'm experiencing a similar behaviour, this is my code:
> 
> ```
> <View
>   style={{
>     flex: 1,
>     alignItems: 'center',
>     justifyContent: 'center',
>   }}>
>   <View
>     style={{
>       width: 200,
>       height: 200,
>     }}>
>     <ReactNativeZoomableView
>       bindToBorders={true}
>       style={{
>         width: 200,
>         height: 200,
>       }}>
>       <Image uri={path} />
>     </ReactNativeZoomableView>
>   </View>
> </View>
> ```
> 
> see attached video that demonstrate the behaviour. I expected the rectangle of the image to remain in same position & size in the screen and not to increase in size will increasing the image, unless I didn't understand the purpose of bindToBorders
> ![Screen-Recording-2020-01-29-at-11 11 11](https://user-images.githubusercontent.com/10025214/73343402-41327500-4289-11ea-987d-49ed90459004.gif)

@tamirla I have checked your example and I your problem is caused by using `alignItems` and `justifyItems`.
In general I would recommend to not wrap the `ReactNativeZoomableView` in the centered content, but rather wrap your "canvas" with `ReactNativeZoomableView`.

```
<ReactNativeZoomableView
  bindToBorders={true}>
  <View
    style={{
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    }}>
    <View
      style={{
        width: 200,
        height: 200,
      }}>
        <Image uri={path} />
    </View>
  </View>
</ReactNativeZoomableView>
```

And generally it is recommended to not add width/height on the `ReactNativeZoomableView` itself.

**Comment by SimonErich** [comment]
> I am using it but my image width is cutting both sides around 10%.

@chandniKkpl I have tried your example, but it works fine so far for me.
Sorry for the delay. DId you solve your problem in the meantime?
If not, maybe try setting `bindToBorders` to `true`.
