### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by SaeedZhiany** [DuDigital/react-native-zoomable-view#29]
I just took a look at code and some questions come in my mind.

1. In [this line](https://github.com/DuDigital/react-native-zoomable-view/blob/80e3ce0e15cae692b36ea101152d46b5ece28750/src/ReactNativeZoomableView.js#L18) why you didn't use PureComponent to reduce unnecessary re-renderings?

2. I'm not much familiar with PanResponder but is it possible to replace it with [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) library to get smooth and robust gesture animation?

**Comment by SimonErich** [comment]
Hey @SaeedZhiany ,

Thanks for your interest in this package.

1.) Some users had a problem using PureComponents in the beginning. Maybe these should be resolved after changing the structure around anyway. Will give it a try again with the next release.

2.) That's actually a very good point, that I have been working on for the last 2 months. The new version of this package will actually only use react-native-gesture-handler and has a much better performance. It already looks really good and we are using it internally in production already. I just didn't have time to completely make it generic and document it properly. I will try to get some time to do this over the christmas holidays.

3.) You are also very welcome to contribute and help on improving this package :) Feel free to send a pull request, if you have ideas

Hope this answers your questions.

**Comment by SimonErich** [comment]
@SaeedZhiany you can find the code in the repo here ;)
