### ISSUE TITLE
ScrollView is inactive

### ISSUE THREAD

**Issue by gshoanganh** [DuDigital/react-native-zoomable-view#31]
If you use **ReactNativeZoomableView** and **ScrollView** simultaneously, **ScrollView** will not work, unfortunately.
e.g:
```
 <ReactNativeZoomableView>
                        <ScrollView>
                               //your content
                       <ScrollView>
<ReactNativeZoomableView>
```

**Comment by skantus** [comment]
@gshoanganh `Scrollview` has zoom properties by defect, for example `zoomScale, bouncesZoom, maximumZoomScale, minimumZoomScale` then you don't need any wrap to do this.

https://facebook.github.io/react-native/docs/scrollview#zoomscale

Ex: https://medium.com/@mheavers/animating-zoom-in-react-native-scroll-view-16587b35a064

I hope this help.

**Comment by TKshadow018** [comment]
Faced the same issue

**Comment by AtulKondekar** [comment]
@gshoanganh @TKshadow018 Did you find any solution for scrolling in iOS device?

**Comment by TKshadow018** [comment]
> @gshoanganh @TKshadow018 Did you find any solution for scrolling in iOS device?

No.

**Comment by AtulKondekar** [comment]
Thanks @TKshadow018  for the reply, I found a way for scroll to work on iOS, we have to add 
` if(gestureState.numberActiveTouches < 2) return false;` 
at the top inside the `_handleMoveShouldSetPanResponder`  function in ReactNativeZoomableView.js file

basically function will look like
`/**
   * Checks if the movement responder should be triggered
   *
   * @param e
   * @param gestureState
   * @returns {Boolean|boolean}
   */
  _handleMoveShouldSetPanResponder = (e, gestureState) => {
    if(gestureState.numberActiveTouches < 2) return false;
    let baseComponentResult =
          this.props.zoomEnabled &&
          (Math.abs(gestureState.dx) > 2 ||
            Math.abs(gestureState.dy) > 2 ||
            gestureState.numberActiveTouches === 2);

    if (this.props.onMoveShouldSetPanResponder) {
      baseComponentResult = this.props.onMoveShouldSetPanResponder(
        e,
        gestureState,
        this._getZoomableViewEventObject(),
        baseComponentResult
      );
    }
    return baseComponentResult;
  };`

**Comment by SimonErich** [comment]
Seems like there is no simple solution for this problem right now using the GestureDetector of react-native, because they steal each others GestureListeners.
If anybody has an idea, please comment here
