### ISSUE TITLE
Programatically move zoomed area

### ISSUE THREAD

**Issue by Nodonisko** [DuDigital/react-native-zoomable-view#34]
Hi,
I need to create something like minimap and when user clicks in minimap I need to move zoomed area to different position, is it possible somehow? Using ref or something like that?

**Comment by SimonErich** [comment]
@Nodonisko unfortunately we don't have that feature yet, but will tag it as a feature request

**Comment by mmskvortsov** [comment]
oh... is there any kind of workaround to zoom programmatically or at least to move the position?

**Comment by mahiraltinkaya** [comment]
Hey;
I want to programmatically change the angle or position of the zoom. Can you suggest a solution?

**Comment by ajayg415** [comment]
when user zoom it using double tap or two fingers, we're updating `zoom, offsetX and offsetY`, if we could update these values programmatically you achieve what you want I guess. refer below sample code. 

```javascript
const doubleTapAfter = useCallback((_event, _gestureState, zoomableViewEventObject) => { 
  const { zoomLevel: zoom, offsetX, offsetY } = zoomableViewEventObject
  savePosition({ zoom, offsetX, offsetY })
}, [])

<ReactNativeZoomableView
  initialZoom={zoom}
  initialOffsetX={offsetX}
  initialOffsetY={offsetY}
  maxZoom={minimumZoom + 1}
  minZoom={1.0}
  zoomStep={0.2}
  bindToBorders={true}
  style={{
      width: maxWidth,
      height: maxHeight,
  }}
  onZoomAfter={zoomHandler}
  onShiftingAfter={movementHandler}
  onDoubleTapAfter={doubleTapAfter}
>
  <Component {...props} />
</ReactNativeZoomableView>
```

**Comment by ajayg415** [comment]
I have this requirement in my project, I'm trying it in my local. I'll raise PR and update once I successful.

**Comment by mahiraltinkaya** [comment]
> I have this requirement in my project, I'm trying it in my local. I'll raise PR and update once I successful.

Thank you bro. I will wait u

**Comment by SimonErich** [comment]
Hey guys,
sorry for the long delay.

Fortuntately we have a new release that introduces events that will help you in that.

Here are the details:
https://github.com/DuDigital/react-native-zoomable-view/releases/tag/v1.1.0

Please make sure to install the latest version. (1.1.3 or up for a working version)
You can also check out the example repo for an examples: 
https://github.com/DuDigital/react-native-zoomable-view
