### ISSUE TITLE
How to animate double tap zoom?

### ISSUE THREAD

**Issue by mammad2c** [DuDigital/react-native-zoomable-view#4]
Hi, 
How can I add a duration to zoom when double tap on photo. Zooming now have no duration and like a flash effect, suddenly zoom in and zoom out. Like twitter or ...

**Comment by SimonErich** [comment]
Hi Mohammed, there is no animation for tap to zoom, because the performance was quite bad, when I tried it.
Will have a look at it at the weekend and maybe give it a go.
If you manage to do it before me, I would appreciate a pull request.

**Comment by SimonErich** [comment]
@mammad2c sorry, I haven't managed to find time to fix this issue.
I have played a round a little bit, but so far the performance is not very good.

I will try to find a solution as soon as possible.
If anyone else finds time to work on this in the meantime, you are more than welcome to open a pull request.

**Comment by mammad2c** [comment]
hi, I will try too. 
thanks

**Comment by SimonErich** [comment]
I have tried, but haven't found a clear way to make this in a performance light way.
I will therefore close this for now. Maybe this will change with react 16.0.0 and the promised performance improvements.
Will give it a try then.
