### ISSUE TITLE
Reset back to initial zoom level

### ISSUE THREAD

**Issue by Dellybro** [DuDigital/react-native-zoomable-view#40]
Is it possible to reset back to initial zoom level?

**Comment by massimoomodei** [comment]
Yes, but only disabling and re-enabling the zoom with the `zoomEnabled` property

**Comment by 3GOMESz** [comment]
Just like @massimoomodei said, you can do this by disabling and re-enabling zoom with the zoomEnabled property, however, it would be interesting to have a future implementation of some easier method for this by a function for example.

**Comment by SimonErich** [comment]
@3GOMESz thank you for helping out here.
Sorry for the delay.

I am closing this for now, but will write this feature request down for the new version.
