### ISSUE TITLE
Pinch gesture not working

### ISSUE THREAD

**Issue by jpmazza** [DuDigital/react-native-zoomable-view#41]
I have a Twilio integration I want to let the user zoom in/out in the remote camera view.

```
<ReactNativeZoomableView
  maxZoom={3}
  minZoom={0.5}
  zoomStep={0.3}
  initialZoom={1}
  captureEvent
>
  <TwilioVideoParticipantView
    style={styles.remoteVideo}
    key={trackSid}
    trackIdentifier={trackIdentifier}
  />
</ReactNativeZoomableView>
```

Double-tap is working properly but the pinch gesture is not working for me. :/

```
"react-native": "~0.61.4"
"@dudigital/react-native-zoomable-view": "^1.0.15"
```

**Comment by johhansantana** [comment]
same here I think it has to do somewhere in [this line](https://github.com/DuDigital/react-native-zoomable-view/blob/80e3ce0e15cae692b36ea101152d46b5ece28750/src/ReactNativeZoomableView.js#L116) the condition there is returning `undefined` always.

**Comment by laraferroni** [comment]
I ran into this as well, and determined it was because I was using it in a modal (specifically, the react-native-base Overlay). When I switched to an absolute positioned view instead, the pinch gesture worked. This appears to be an issue with the react-native-gesture-handler in modals.

**Comment by michaelVictoriaDev** [comment]
captureEvent={true} is having more warning error logs,

**Comment by ph-sw** [comment]
captureEvent={true} makes it work in Modal for me also. However, the zoom in and panning is not bound by the border of the view encapsulating the ReachNativeZoomableView component.

**Comment by SimonErich** [comment]
@laraferroni thanks for helping out here, I really appreciate it :)
@ph-sw can you give a bit more information about the problem?
It's important, that ReactNativeZoomableView covers the whole area, that you want to be "gesturable" otherwise we cannot listen to it.

**Comment by SimonErich** [comment]
Closed because no reply was given.
