### ISSUE TITLE
You Can Just Use ScrollView Instead (not an issue)

### ISSUE THREAD

**Issue by nescroft** [DuDigital/react-native-zoomable-view#43]
I found that all I needed for zoom was this. I'm not sure how to do double click to zoom but I don't really need it for my app. I just put this here for other people who might be having problems with react-native-zoomable-view.

`<ScrollView
        bounces={false}
        bouncesZoom={false}
        maximumZoomScale={2}
        minimumZoomScale={1}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}>
/*your content*/
</ScrollView>`

**Comment by nescroft** [comment]
``

**Comment by cuddeford** [comment]
This has blown my mind

**Comment by webtaculars** [comment]
Just to put it, your solution only works for iOS. So if anyone isn't building for android, then this is great

**Comment by nescroft** [comment]
> Just to put it, your solution only works for iOS. So if anyone isn't building for android, then this is great

yeah i realized that eventually.. if anyone has an easy solution like this for android i'd be interested to see it. it works great on ios.
