### ISSUE TITLE
Webpack complie error

### ISSUE THREAD

**Issue by chkrause** [DuDigital/react-native-zoomable-view#47]
Tried to use module in expo Framework, but got following error when trying to open in WebBrowser

Module parse failed: Unexpected token (66:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|    * @type {number}
|    */
>   longPressTimeout = null;
|      
|   /**

**Comment by SimonErich** [comment]
@chkrause this is weird. There is nothing really special there.
Did you manage to solve it?
Do use typescript in your project?
