### ISSUE TITLE
Invalid dependency '@dudigital/react-native-zoomable-view/src/ReactNativeZoomableView' (name can only contain URL-friendly characters)

### ISSUE THREAD

**Issue by mcsalinda** [DuDigital/react-native-zoomable-view#48]
Hi, 
Please check the above issue. It seems the name is invalid as per the error code.
https://snack.expo.io/SkltQtr8Q

**Comment by SimonErich** [comment]
@mcsalinda you are using a wrong package name in package.json.
If you follow the instructions in readme, you get the following package.json:
```
{
  "dependencies": {
    "react-native-elements": "0.19.1",
    "@dudigital/react-native-zoomable-view": "1.0.7"
  }
}
```
