### ISSUE TITLE
How to set zoom level with button plus/subtract ??? 

### ISSUE THREAD

**Issue by trungdh-pnc** [DuDigital/react-native-zoomable-view#59]
help me please 🥺

**Comment by ajayg415** [comment]
It involves 2 things. 

1. You have to trigger touch event when user clicks **`Plus`** or **`Minus`** buttons. 
2. Seems the current logic doesn't permit `Minus` operation, you have to add this new functionality in [ReactNativeZoomableView.js](https://github.com/DuDigital/react-native-zoomable-view/blob/master/src/)

**Comment by SimonErich** [comment]
thank you @ajayg415 for helping out! :)

Fortuntately we have a new release that introduces events exactly for that:

Here are the details:
https://github.com/DuDigital/react-native-zoomable-view/releases/tag/v1.1.0

Please make sure to install the latest version. (1.1.3 or up for a working version)
You can also check out the example repo for an examples: 
https://github.com/DuDigital/react-native-zoomable-view
