### ISSUE TITLE
Cannot pan the view while zoomed in

### ISSUE THREAD

**Issue by alexyangjie** [DuDigital/react-native-zoomable-view#7]
Hi, 

I am trying to build a feature to pan and zoom the image using the ReactNativeZoomableView, and find that the zoomed in view cannot be moved around. The screenshots in the documentation illustrate this capability, so I download the code example and run in with latest expo SDK, and still cannot move the view as showed in the documentation. 

The pan functionality is only working if I double tap to zoom in. If I pin-zoom the view, I am no longer able to pan the view unless I exit and re-enter the screen. 

Could you please provide an example of how the view can be panned and moved? Thanks

**Comment by jannunen** [comment]
I tried to use pan responder. I made a reference to the object and used .zoomToLocation and achieved a click and zoom to a location.

But I didn't manage to get it work smoothly by panning around the screen as in the example or the Expo project (https://snack.expo.io/Sk1BzKdL4)

Any help would be appreciated with the panning.

**Comment by SimonErich** [comment]
Hey guys, sorry for the late response.
There was indeed an issue with releasing the pinch-to-zoom state. Should be fixed now with #8.
Please use v1.0.12
