### ISSUE TITLE
Not working in Modal

### ISSUE THREAD

**Issue by farrukhhashmi65** [DuDigital/react-native-zoomable-view#9]
It is not working in React Native Modal, Any reason or solution for that?

**Comment by SimonErich** [comment]
Hey @farrukhhashmi65,
what modal are you using?
Can you provide a code snippet with your implementation, then I can have a look.
thanks

**Comment by SimonErich** [comment]
Closed because no further info was given.

**Comment by D4vidM** [comment]
Hi! Its not working with standard React Native Modal (import {Modal} from "react-native";)

                <Modal
                    animationType="fade"
                    transparent={false}
                    visible={this.state.modalVisible}
                    enableSwipeDown={false}
                  >
                    <ReactNativeZoomableView
                        zoomEnabled={true}
                        movementSensibility={1}
                        maxZoom={1.5}
                        minZoom={0.5}
                        zoomStep={0.5}
                        initialZoom={1}
                        bindToBorders={false}
                        onZoomAfter={this.logOutZoomState}
                        style={{width: Dimensions.get('window').width, height: Dimensions.get('window').height, alignItems: 'center', justifyContent: 'center'}}
                    >
                        <Image
                            source={this.props.source}
                            resizeMode={'contain'}
                            resizeMethod={'scale'}
                        />
                    </ReactNativeZoomableView>

                    <TouchableOpacity
                        style={{position: 'absolute', bottom: 30, right: 30, zIndex: 2, alignItems: 'center', justifyContent: 'center'}}
                        onPress={() => {
                          this.setModalVisible(!this.state.modalVisible);
                        }}
                    >
                        <Ionicons style={{opacity: 0.7}} name="md-close-circle-outline" size={40} color="#757B7F" />
                    </TouchableOpacity>

                </Modal>


It zooms in on double tap but pan to move and pinch to zoom are not working

**Comment by SimonErich** [comment]
@farrukhhashmi65 @D4vidM I have just released v1.0.15 with a new property `captureEvent`.
If you set this property to `true` it should work in react-native modals.
Can you please give it a try and let me know if it works?

Thanks

**Comment by douglasjunior** [comment]
Worked with `captureEvent`.
